### ISSUE TITLE
The problem is i don't have twitter enterprise account

### ISSUE THREAD

**Issue by Gary-Hertel** [twitterdev/enterprise-scripts-python#7]
I want to establish a power track stream connection, so i can receive tweets from twitter. I am using free stream api, but it has a delay, it is about 5 seconds, i want to find a better solution, power track may be better.

**Comment by andypiper** [comment]
You can use the [Enterprise Access form](https://t.co/enterprise-access) to contact the sales team. This repository if for scripts to manage PowerTrack connections, not for general enquiries. You can also use the [Developer Community Forum](https://twittercommunity.com).
